# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wigle-GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import sys, os, qdarkstyle
from configparser import ConfigParser
from PyQt5.QtWidgets import QMessageBox, QInputDialog, QTableWidgetItem, QTableWidget
from colorama import *

class Ui_MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.conf = ConfigParser()
        self.conf.read('config.ini')
        self.wep_list = []
        self.wpa_list = []
        self.tp_link_list = []
        self.o2_list = []
        self.variables()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_scan = QtWidgets.QPushButton(self.centralwidget)
        self.button_scan.setGeometry(QtCore.QRect(470, -10, 171, 71))
        self.button_scan.setStyleSheet("color : rgb(26, 95, 180)")
        self.button_scan.setObjectName("button_scan")
        self.button_settings = QtWidgets.QPushButton(self.centralwidget)
        self.button_settings.setGeometry(QtCore.QRect(640, -10, 131, 71))
        self.button_settings.setStyleSheet("color : rgb(38, 162, 105)")
        self.button_settings.setObjectName("button_settings")
        self.button_info = QtWidgets.QPushButton(self.centralwidget)
        self.button_info.setGeometry(QtCore.QRect(770, -10, 121, 71))
        self.button_info.setStyleSheet("color : rgb(229, 165, 10)")
        self.button_info.setObjectName("button_info")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(890, -10, 131, 71))
        self.button_exit.setStyleSheet("color: rgb(165, 29, 45)")
        self.button_exit.setObjectName("button_exit")
        self.wep_networks_label = QtWidgets.QLabel(self.centralwidget)
        self.wep_networks_label.setGeometry(QtCore.QRect(30, 120, 401, 19))
        self.wep_networks_label.setStyleSheet("color : rgb(192, 28, 40)")
        self.wep_networks_label.setObjectName("wep_networks_label")
        self.csv_path_label = QtWidgets.QLabel(self.centralwidget)
        self.csv_path_label.setGeometry(QtCore.QRect(0, 0, 471, 31))
        self.csv_path_label.setObjectName("csv_path_label")
        self.csv_path_button = QtWidgets.QPushButton(self.centralwidget)
        self.csv_path_button.setGeometry(QtCore.QRect(0, 30, 471, 27))
        self.csv_path_button.setObjectName("csv_path_button")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(470, 60, 171, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.wpa_networks_label = QtWidgets.QLabel(self.centralwidget)
        self.wpa_networks_label.setGeometry(QtCore.QRect(30, 150, 401, 19))
        self.wpa_networks_label.setStyleSheet("color : rgb(26, 95, 180)")
        self.wpa_networks_label.setObjectName("wpa_networks_label")
        self.o2_networks_labe = QtWidgets.QLabel(self.centralwidget)
        self.o2_networks_labe.setGeometry(QtCore.QRect(30, 180, 401, 19))
        self.o2_networks_labe.setStyleSheet("color : rgb(97, 53, 131)")
        self.o2_networks_labe.setObjectName("o2_networks_labe")
        self.tp_link_networks_label = QtWidgets.QLabel(self.centralwidget)
        self.tp_link_networks_label.setGeometry(QtCore.QRect(30, 210, 401, 19))
        self.tp_link_networks_label.setStyleSheet("color : rgb(38, 162, 105)")
        self.tp_link_networks_label.setObjectName("tp_link_networks_label")
        self.in_total_networks_label = QtWidgets.QLabel(self.centralwidget)
        self.in_total_networks_label.setGeometry(QtCore.QRect(30, 240, 401, 19))
        self.in_total_networks_label.setObjectName("in_total_networks_label")
        self.wep_scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.wep_scroll_area.setGeometry(QtCore.QRect(0, 330, 441, 181))
        self.wep_scroll_area.setWidgetResizable(True)
        self.wep_scroll_area.setObjectName("wep_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.wep_table_view = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.wep_table_view.setGeometry(QtCore.QRect(0, 0, 441, 192))
        self.wep_table_view.setObjectName("wep_table_view")
        self.wep_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.wep_label = QtWidgets.QLabel(self.centralwidget)
        self.wep_label.setGeometry(QtCore.QRect(180, 280, 121, 51))
        self.wep_label.setStyleSheet("color: rgb(165, 29, 45)")
        self.wep_label.setObjectName("wep_label")
        self.o2_scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.o2_scroll_area.setGeometry(QtCore.QRect(0, 570, 441, 181))
        self.o2_scroll_area.setWidgetResizable(True)
        self.o2_scroll_area.setObjectName("o2_scroll_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 439, 179))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.o2_table_view = QtWidgets.QTableView(self.scrollAreaWidgetContents_2)
        self.o2_table_view.setGeometry(QtCore.QRect(0, 0, 441, 192))
        self.o2_table_view.setObjectName("o2_table_view")
        self.o2_scroll_area.setWidget(self.scrollAreaWidgetContents_2)
        self.wpa_scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.wpa_scroll_area.setGeometry(QtCore.QRect(490, 330, 441, 181))
        self.wpa_scroll_area.setWidgetResizable(True)
        self.wpa_scroll_area.setObjectName("wpa_scroll_area")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 439, 179))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.wpa_table_view = QtWidgets.QTableView(self.scrollAreaWidgetContents_3)
        self.wpa_table_view.setGeometry(QtCore.QRect(-10, 0, 441, 192))
        self.wpa_table_view.setObjectName("wpa_table_view")
        self.wpa_scroll_area.setWidget(self.scrollAreaWidgetContents_3)
        self.tp_link_scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.tp_link_scroll_area.setGeometry(QtCore.QRect(490, 570, 441, 181))
        self.tp_link_scroll_area.setWidgetResizable(True)
        self.tp_link_scroll_area.setObjectName("tp_link_scroll_area")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 439, 179))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.tp_link_table_view = QtWidgets.QTableView(self.scrollAreaWidgetContents_4)
        self.tp_link_table_view.setGeometry(QtCore.QRect(0, 0, 441, 192))
        self.tp_link_table_view.setObjectName("tp_link_table_view")
        self.tp_link_scroll_area.setWidget(self.scrollAreaWidgetContents_4)
        self.tp_link_label = QtWidgets.QLabel(self.centralwidget)
        self.tp_link_label.setGeometry(QtCore.QRect(650, 510, 121, 61))
        self.tp_link_label.setStyleSheet("color: rgb(165, 29, 45)")
        self.tp_link_label.setObjectName("tp_link_label")
        self.o2_label = QtWidgets.QLabel(self.centralwidget)
        self.o2_label.setGeometry(QtCore.QRect(170, 510, 121, 61))
        self.o2_label.setStyleSheet("color: rgb(129, 61, 156)")
        self.o2_label.setObjectName("o2_label")
        self.wpa_label = QtWidgets.QLabel(self.centralwidget)
        self.wpa_label.setGeometry(QtCore.QRect(660, 280, 121, 51))
        self.wpa_label.setStyleSheet("color : rgb(26, 95, 180)")
        self.wpa_label.setObjectName("wpa_label")
        self.made_by_label = QtWidgets.QLabel(self.centralwidget)
        self.made_by_label.setGeometry(QtCore.QRect(640, 80, 161, 19))
        self.made_by_label.setObjectName("made_by_label")
        self.made_in_label = QtWidgets.QLabel(self.centralwidget)
        self.made_in_label.setGeometry(QtCore.QRect(810, 80, 161, 19))
        self.made_in_label.setObjectName("made_in_label")
        self.sourcelabel = QtWidgets.QLabel(self.centralwidget)
        self.sourcelabel.setGeometry(QtCore.QRect(640, 60, 371, 19))
        self.sourcelabel.setObjectName("sourcelabel")
        MainWindow.setCentralWidget(self.centralwidget)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_exit.clicked.connect(self.close)
        self.csv_path_button.clicked.connect(self.csv_input_func)
        self.button_scan.clicked.connect(self.scan)



        self.show()

    def retranslateUi(self, MainWindow):
        if self.conf['Language']['not_set'] == 'true' or self.conf['Language']['english'] == 'true':

            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.button_scan.setText(_translate("MainWindow", "Scan"))
            self.button_settings.setText(_translate("MainWindow", "Settings"))
            self.button_info.setText(_translate("MainWindow", "Info"))
            self.button_exit.setText(_translate("MainWindow", "Exit"))
            self.wep_networks_label.setText(_translate("MainWindow", "WEP Networks: "))
            self.csv_path_label.setText(_translate("MainWindow", "CSV:  None"))
            self.csv_path_button.setText(_translate("MainWindow", "Choose CSV file"))
            self.wpa_networks_label.setText(_translate("MainWindow", "WPA Networks: "))
            self.o2_networks_labe.setText(_translate("MainWindow", "O2 Networks: "))
            self.tp_link_networks_label.setText(_translate("MainWindow", "TP-Link Networks: "))
            self.in_total_networks_label.setText(_translate("MainWindow", "In total:"))
            self.wep_label.setText(_translate("MainWindow", "WEP:"))
            self.tp_link_label.setText(_translate("MainWindow", "TP-Link:"))
            self.o2_label.setText(_translate("MainWindow", "O2:"))
            self.wpa_label.setText(_translate("MainWindow", "WPA:"))
            self.made_by_label.setText(_translate("MainWindow", "Made by EchterAlsFake"))
            self.made_in_label.setText(_translate("MainWindow", "Made in Germany"))
            self.sourcelabel.setText(_translate("MainWindow", "Source: https://github.com/echteralsfake/wigle-extract"))

        elif self.conf['Language']['german'] == 'true':
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.button_scan.setText(_translate("MainWindow", "Scan"))
            self.button_settings.setText(_translate("MainWindow", "Einstellungen"))
            self.button_info.setText(_translate("MainWindow", "Info"))
            self.button_exit.setText(_translate("MainWindow", "Exit"))
            self.wep_networks_label.setText(_translate("MainWindow", "WEP Netzwerke: "))
            self.csv_path_label.setText(_translate("MainWindow", "CSV:  Keine Auswahl"))
            self.csv_path_button.setText(_translate("MainWindow", "CSV auswählen"))
            self.wpa_networks_label.setText(_translate("MainWindow", "WPA Netzwerke: "))
            self.o2_networks_labe.setText(_translate("MainWindow", "O2 Netzwerke: "))
            self.tp_link_networks_label.setText(_translate("MainWindow", "TP-Link Netzwerke: "))
            self.in_total_networks_label.setText(_translate("MainWindow", "Insgesamt:"))
            self.wep_label.setText(_translate("MainWindow", "WEP:"))
            self.tp_link_label.setText(_translate("MainWindow", "TP-Link:"))
            self.o2_label.setText(_translate("MainWindow", "O2:"))
            self.wpa_label.setText(_translate("MainWindow", "WPA:"))
            self.made_by_label.setText(_translate("MainWindow", "Made by EchterAlsFake"))
            self.made_in_label.setText(_translate("MainWindow", "Made in Deutschland"))
            self.sourcelabel.setText(_translate("MainWindow", "Quelle: https://github.com/echteralsfake/wigle-extract"))


    def scan(self):

        self.vulnerability_search()
        self.progressBar.setValue(33)
        self.clear_lists()
        self.progressBar.setValue(66)
        self.get_results()
        self.progressBar.setValue(100)
        self.show_results()

    def csv_input_func(self):
        self.text, ok = QInputDialog.getText(self, 'Input Dialog', 'Enter text:')
        print(self.text)
        if os.path.exists(str(self.text)):
            self.csv_path_label.setText(str(self.text))

        elif not os.path.exists(str(self.text)):
            self.show_dialog()

    def show_dialog(self):
        msg = QMessageBox(self)
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Path is invalid.  Try again.")
        msg.setWindowTitle("Invalid Path")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.show()
        msg.buttonClicked.connect(self.csv_input_func)
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:
            msg.close()

    def vulnerability_search(self):


        with open(self.text, 'r', encoding="utf-8", errors="replace") as csv_file:
            print(Fore.LIGHTGREEN_EX + "[+] " + Fore.LIGHTCYAN_EX + "Analyzing data....")
            text = csv_file.read().splitlines()
            for line in text:
                if ",," in str(line):
                    pass

                if self.wep:

                    if "WEP" and ",," in str(line):
                        pass

                    elif "WEP" in str(line):
                        self.wep_list.append(line)

                if self.wps_o2:

                    if "o2-WLAN" in str(line):
                        self.o2_list.append(line)

                if self.wps_tp_link:
                    if "tp-link" in str(line):
                        self.tp_link_list.append(line)

                    elif "TP-Link" in str(line):
                        self.tp_link_list.append(line)

                if self.wpa:
                    if "WPA-PSK-TKIP" and "WPA2" in str(line):
                        pass

                    elif "WPA-PSK-TKIP" in str(line):
                        self.wpa_list.append(line)

    def clear_lists(self):
        self.cleared_wep_list = {}
        self.cleared_o2_list = {}
        self.cleared_tp_link_list = {}
        self.cleared_wpa_list = {}

        for item in self.wep_list:
            values = item.split(",")
            mac = values[0]
            if mac not in self.cleared_wep_list:
                self.cleared_wep_list[mac] = values

            else:
                pass

        for item in self.o2_list:
            values = item.split(",")
            mac = values[0]
            if mac not in self.cleared_o2_list:
                self.cleared_o2_list[mac] = values

            else:
                pass

        for item in self.tp_link_list:
            values = item.split(",")
            mac = values[0]
            if mac not in self.cleared_tp_link_list:
                self.cleared_tp_link_list[mac] = values

            else:
                pass

        for item in self.wpa_list:
            values = item.split(",")
            mac = values[0]
            if mac not in self.cleared_wpa_list:
                self.cleared_wpa_list[mac] = values

            else:
                pass

    def variables(self):

        if self.conf['WPS']['tp_link'] == 'true':
            self.wps_tp_link = True
            self.wps_tp_link_ext = Fore.LIGHTGREEN_EX + "Enabled"

        elif self.conf['WPS']['tp_link'] == 'false':
            self.wps_tp_link = False
            self.wps_tp_link_ext = Fore.LIGHTRED_EX + "Disabled"

        if self.conf['WPS']['o2'] == 'true':
            self.wps_o2 = True
            self.wps_o2_ext = Fore.LIGHTGREEN_EX + "Enabled"

        elif self.conf['WPS']['o2'] == 'false':
            self.wps_o2 = False
            self.wps_o2_ext = Fore.LIGHTRED_EX + "Disabled"

        if self.conf['WPA']['tkip'] == 'true':
            self.wpa = True
            self.wpa_ext = Fore.LIGHTGREEN_EX + "Enabled"

        elif self.conf['WPA']['tkip'] == 'false':
            self.wpa = False
            self.wpa_ext = Fore.LIGHTRED_EX + "Disabled"

        if self.conf['WEP']['wep'] == 'true':
            self.wep = True
            self.wep_ext = Fore.LIGHTGREEN_EX + "Enabled"

        elif self.conf['WEP']['wep'] == 'false':
            self.wep = False
            self.wep_ext = Fore.LIGHTRED_EX + "Disabled"

        else:
            print("Variables not loaded.")

    def get_results(self):

        self.clear_lists()
        self.wep_length = len(self.cleared_wep_list)
        self.o2_length = len(self.cleared_o2_list)
        self.tp_link_length = len(self.cleared_tp_link_list)
        self.wpa_length = len(self.cleared_wpa_list)
        self.all_length = self.wep_length + self.o2_length + self.tp_link_length + self.wpa_length

    def show_results(self):
        self.show_wep()
        self.show_wpa()
        self.show_o2()
        self.show_tp_link()

    def show_wep(self):
        table = QTableWidget()
        table.setRowCount(len(self.cleared_wep_list))
        table.setColumnCount(4)
        table.setHorizontalHeaderLabels(["MAC", "Name", "Latitude", "Longitude"])
        row = 0
        for mac in self.cleared_wep_list:
            values = self.cleared_wep_list[mac]
            mac = values[0]
            name = values[1]
            gps_latitude = values[6]
            gps_longitude = values[7]
            table.setItem(row, 0, QTableWidgetItem(mac))
            table.setItem(row, 1, QTableWidgetItem(name))
            table.setItem(row, 2, QTableWidgetItem(gps_latitude))
            table.setItem(row, 3, QTableWidgetItem(gps_longitude))

            row += 1

        table.resizeColumnsToContents()
        self.wep_scroll_area.setWidget(table)
        self.wep_scroll_area.show()

    def show_wpa(self):
        table = QTableWidget()
        table.setRowCount(len(self.cleared_wpa_list))
        table.setColumnCount(4)
        table.setHorizontalHeaderLabels(["MAC", "Name", "Latitude", "Longitude"])
        row = 0
        for mac in self.cleared_wpa_list:
            values = self.cleared_wpa_list[mac]
            mac = values[0]
            name = values[1]
            gps_latitude = values[6]
            gps_longitude = values[7]
            table.setItem(row, 0, QTableWidgetItem(mac))
            table.setItem(row, 1, QTableWidgetItem(name))
            table.setItem(row, 2, QTableWidgetItem(gps_latitude))
            table.setItem(row, 3, QTableWidgetItem(gps_longitude))

            row += 1

        table.resizeColumnsToContents()
        self.wpa_scroll_area.setWidget(table)
        self.wpa_scroll_area.show()

    def show_o2(self):

        table = QTableWidget()
        table.setRowCount(len(self.cleared_o2_list))
        table.setColumnCount(4)
        table.setHorizontalHeaderLabels(["MAC", "Name", "Latitude", "Longitude"])
        row = 0
        for mac in self.cleared_o2_list:
            values = self.cleared_o2_list[mac]
            mac = values[0]
            name = values[1]
            gps_latitude = values[6]
            gps_longitude = values[7]
            table.setItem(row, 0, QTableWidgetItem(mac))
            table.setItem(row, 1, QTableWidgetItem(name))
            table.setItem(row, 2, QTableWidgetItem(gps_latitude))
            table.setItem(row, 3, QTableWidgetItem(gps_longitude))

            row += 1

        table.resizeColumnsToContents()
        self.o2_scroll_area.setWidget(table)
        self.o2_scroll_area.show()

    def show_tp_link(self):

        table = QTableWidget()
        table.setRowCount(len(self.cleared_tp_link_list))
        table.setColumnCount(4)
        table.setHorizontalHeaderLabels(["MAC", "Name", "Latitude", "Longitude"])
        row = 0
        for mac in self.cleared_tp_link_list:
            values = self.cleared_tp_link_list[mac]
            mac = values[0]
            name = values[1]
            gps_latitude = values[6]
            gps_longitude = values[7]
            table.setItem(row, 0, QTableWidgetItem(mac))
            table.setItem(row, 1, QTableWidgetItem(name))
            table.setItem(row, 2, QTableWidgetItem(gps_latitude))
            table.setItem(row, 3, QTableWidgetItem(gps_longitude))

            row += 1

        table.resizeColumnsToContents()
        self.tp_link_scroll_area.setWidget(table)
        self.tp_link_scroll_area.show()



app = QtWidgets.QApplication(sys.argv)
windows = Ui_MainWindow()
app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
sys.exit(app.exec_())